#!/bin/sh



# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

if [[ -z "$PATH" || "$PATH" == "/bin:/usr/bin" ]]; then export PATH="/usr/local/bin:/usr/bin:/bin:/usr/games"; fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then PATH="$HOME/bin:$PATH" ; fi

# set PATH so it includes zshrc file if it exists
#if [ -f "$HOME/.config/zsh/zshrc" ]; then source "$HOME/.config/zsh/zshrc"; fi

# shellcheck disable=SC2155

# Profile file, runs on login. Environmental variables are set here.

# Add all directories in `~/.local/bin` to $PATH
#export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

# Default programs:
# export NVIM_PATH="/media/ahmdhosni/Storage/apps/neovim/nvim/nvim-linux.appimage"
# export EDITOR=$NVIM_PATH visudo
# export VISUAL=$NVIM_PATH visudo
# export SUDO_EDITOR="$NVIM_PATH"
# export FCEDIT=$NVIM_PATH
# export TERMINAL=kitty
# export TERMINAL_PROG=kitty
# export BROWSER=firefox

# Default programs:
export EDITOR=nvim visudo
export VISUAL=nvim visudo
export SUDO_EDITOR=nvim
export SYSTEMD_EDITOR=nvim
export FCEDIT=nvim
export TERMINAL=kitty
export BROWSER=firefox


# Force Dark theme
#export GTK_THEME=Adwaita:dark


# bat environmental variable if exists
if [[ -x "$(command -v bat)" ]]; then
	export MANPAGER="sh -c 'col -bx | bat -l man -p'"
	export PAGER=bat
fi

# batcat environmental variable if exists
if [[ -x "$(command -v batcat)" ]]; then
	export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
	export PAGER=batcat
fi






# Change the default crypto/weather monitor sites.
# export CRYPTOURL="rate.sx"
# export WTTRURL="wttr.in"

###################
# Main Directories:
###################


export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

#####################
# Custom Directories:
# ###################

## zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

## git
# 1. Force Git to look for its main config in XDG
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"
# 2. Tell Git where the global ignore and attributes are
if command -v git &>/dev/null; then
    git config --global core.excludesFile "$XDG_CONFIG_HOME/git/ignore"
    git config --global core.attributesFile "$XDG_CONFIG_HOME/git/attributes"
    # 3. Force credentials to XDG (if using 'store' helper)
    git config --global credential.helper "store --file $XDG_CONFIG_HOME/git/credentials"
fi

## npm
# Tell npm to use XDG directories
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_PREFIX="$XDG_DATA_HOME/npm"
# Add the global bin directory to your PATH
export PATH="$XDG_DATA_HOME/npm/bin:$PATH"


## Rust
export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"


## Ollama
export OLLAMA_MODELS=$XDG_DATA_HOME/ollama/models

## OpenCode
OPENCODE_CONFIG_DIR=$XDG_CONFIG_HOME/opencode
OPENCODE_CONFIG=$OPENCODE_CONFIG_DIR/opencode.json


## claud Cli 
export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"


## vsCode
# VSCODE_PORTABLE="/media/ahmdhosni/Storage/Apps/vsCode/VSCode"
# export VSCODE_APPDATA="$VSCODE_PORTABLE/data/user-data"
# export VSCODE_EXTENSIONS="$VSCODE_PORTABLE/data/extensions"
export PLATFORMIO_CORE_DIR="$XDG_DATA_HOME/vsCode/extensions/platformio"


## Java (openJDK)
#export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
#export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
#
# Java Location (Debian standard path for OpenJDK 17)
#export JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64
#export JAVA_HOME="/media/ahmdhosni/Storage/Apps/Android/Sdk/Jdk/jdk-25.0.2"
#export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
#export JAVA_FONTS="$HOME/.local/share/fonts"
#export _JAVA_OPTIONS="$XDG_CONFIG_HOME"/java
#export _JAVA_OPTIONS="-Duser.home=$XDG_CONFIG_HOME"
#export JAVA_TOOL_OPTIONS="-Duser.home=$XDG_DATA_HOME/java"



#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"

#export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
#export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
#export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
#export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"

## Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS="R"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2"        # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2=1                  # Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1      # Fix for Java applications in dwm

#[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1

# Start graphical server on user's current tty if not already running.
#[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Switch escape and caps if tty and no passwd required:
#sudo -n loadkeys "$XDG_DATA_HOME/larbs/ttymaps.kmap" 2>/dev/null



#################
# Extra exports :
# ##############
if [ -f /usr/share/zsh/zshExtras/exports/exports.zsh ]; then source /usr/share/zsh/zshExtras/exports/exports.zsh; fi




